SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Actividades]
(
    [idActividad] [UNIQUEIDENTIFIER] NOT NULL,
    [Descripcion] [VARCHAR](100) NOT NULL,
    [idTipoActividad] [UNIQUEIDENTIFIER] NULL,
    [CentroCosto] [VARCHAR](5) NULL,
    CONSTRAINT [PK_Actividades] PRIMARY KEY CLUSTERED 
(
	[idActividad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
