SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Jornada_Bitacora_UnidadNegocio]
(
    [idUnidadNegocio] [UNIQUEIDENTIFIER] NOT NULL,
    [Descripcion] [VARCHAR](max) NULL,
    CONSTRAINT [PK_Jornada_Bitacora_UnidadNegocio] PRIMARY KEY CLUSTERED 
(
	[idUnidadNegocio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
